---
title: "Pstat231HW2"
author: "Wentao Yu"
date: '2022-10-04'
output: html_document
---
```{r load package, include=FALSE}
library(tidymodels)
library(tidyverse)
```

##### Question 1
```{r read dataset Question 1}
data1 <- read.csv('/Users/wentaoyu/Documents/UCSB File/Stats/Pstat131/Pstat131/homework-2/homework-2/data/abalone.csv') # import dataset
#data1 <- read.csv('D:/Github/Pstat131/homework-2/homework-2/data/abalone.csv')
age <- data1[9]+1.5 # extract the rings column since age = rings+1.5
data2 <- cbind(data1,age) # add a new column into the dataframe
names(data2)[10] <- 'age' # rename the new column as age
ggplot(data2, aes(age))+
  geom_histogram(col='white', binwidth = 1) # plot the age column using histogram to make it access.
```
The distribution of age is more likely a normal distribution with positive skew.

##### Question 2
```{r Question 2 Data Split}
set.seed(4177) # set seed to make sure the output is stable
data3 = subset(data2, select = -c(rings)) # new dataframe exclude rings
abalone_split <- initial_split(data3, prop = 0.80) # split the data set, then what is the appropriate percentage, may need a new data set since we cannot include rings and age????
abalone_training <- training(abalone_split) # this is training data set
abalone_testing <- testing(abalone_split) # this is testing data set
```

##### Question 3
```{r recipe abalone}
#simple_abalone_recipe <- recipe(age~.,data = abalone_training)
abalone_recipe <- recipe(age~., data = abalone_training) %>%
  step_dummy_multi_choice(all_nominal_predictors()) %>%
  step_interact(terms = ~ shucked_weight:type_yes+
                  diameter:longest_shell+
                  shell_weight:shucked_weight) %>%
  #step_interact(terms = ~ diameter:longest_shell) %>% 
  #step_interact(terms = ~ shell_weight:shucked_weight) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())
summary(abalone_recipe)
```

##### Question 4
```{r lm engine}
lm_model <- linear_reg() %>%
  set_engine('lm') # create and store a linear regression object
lm_model
```

##### Question 5
```{r}
lm_workflow <- workflow() %>% # set up a new workflow
  add_model(lm_model) %>% # add the linear model from question 4
  add_recipe(abalone_recipe) # add the recipe from question 3
lm_workflow
```

##### Question 6
```{r fit linear model}
lm_fit <- fit(lm_workflow, abalone_training)
```

##### Required For 231 Students
##### Question 8
Var($\hat{f}(x_0)$) and $Bias(\hat{f}(x_0))^2$ are the reproducible errors.

Var($\epsilon$) is the irreducible error. 

##### Question 9


##### Question 10









